### ISSUE TITLE
Tests are failing all the time

### ISSUE THREAD

**Issue by dmpetrov** [iterative/datachain#285]
Our test are always fail in the past days: Studio & Tutorials. We need to do something about this.
<img width="143" alt="Screenshot 2024-08-12 at 6 06 54 PM" src="https://github.com/user-attachments/assets/0f9cadf7-f736-4922-a39e-92d870af05a4">

**Comment by mattseddon** [comment]
The quick solution would be to merge #292 or #293. The correct solution is to invest some more time into https://github.com/iterative/studio/pull/10429

**Comment by dreadatour** [comment]
Tests are fixed in https://github.com/iterative/datachain/pull/296 + https://github.com/iterative/studio/pull/10471

May be we should have two separate GitHub Actions, one for CLI tests and examples and badge will depends on it, and another separate one is for Studio tests and it will not affects badge but still will be visible in PR? I am not sure if this is possible though 👀

**Comment by dreadatour** [comment]
Like this: https://github.com/iterative/datachain/pull/308
