### ISSUE TITLE
Match image masks with the images they overlay

### ISSUE THREAD

**Issue by djsauble** [iterative/datachain#286]
### Description

If I run a query that produces a dataset with multiple images and multiple image masks, I want to associate each image mask with the image it overlays.

If DataChain doesn't provide a heuristic or data model out of the box which defines this association, users will have to develop non-standard ways to do this, which isn't ideal.

**Comment by volkfox** [comment]
This problem covers several topics:

Q1. How masks and bboxes are associated with images in general
Q2. How the GUI knows where masks and bboxes are, and in which format they are provided
Q3. How the user chooses to see or not see the visual overlays

Answers:

A1.  Images are (typically) file records. Masks and boxes can be associated with file records in one of the two ways:
   *  One row = one mask or one bounding box. The same file record can be repeated on several rows. Arranging metadata in this format is shown in the [COCO mini-tutorial](https://github.com/iterative/datachain-examples/blob/main/formats/json-metadata-tutorial.ipynb)
   * One row = one file record. Masks or bboxes are an array in **some** column of this record.

A2, A3.  A rigid way to locate (e.g. Voxel51) is to require a fixed, well-known column name for masks or bboxes, and a fixed format. This is likely not ideal for datachain.  

A preferred way is to "cast" a visualization layer on a column, e..g. right-click and select "Visualize as bbox" on a column. Since there are several ways to provide bboxes coordinates, we might need sub-options as well – or require one fixed order of coordinates. It also rather straightforward to see if the selected column hosts a list (array of arrays), or a single bbox/mask array entry, so we need to visualize one or more objects per image.

This concludes the required visualization features.

Optional.
A2.1 (see A1.1).   If the dataset is set in such way that there is one bbox/mask per row, the user might be interested in seeing all bboxes or masks on the image (at least temporarily). This mandates a Group command in GUI which (when cast on a column) aggregates entries sharing the same value into subgroup, and visualizes attributes together.

For example, consider the following dataset before grouping by column "file":

file             bbox            (visual picture)
cat.jpg.     box1           box1 over cat.jpg
cat.jpg.     box2          box2 over cat.jpg
dog.jpg.    box1          box1 over dog.jpg

And after grouping:

file        bbox                (visual picture)
cat.jpg                        box1, box2 over cat.jpg
         -- box1               box1 over cat.jpg
         -- box2              box2 over cat.jpg
dog.jpg                       box1 over dog.jpg
        --box1                 box1 over dog.jpg

**Comment by shcheklein** [comment]
@dreadatour also relevant to the bounding boxes, etc?

**Comment by dreadatour** [comment]
> [@dreadatour](https://github.com/dreadatour) also relevant to the bounding boxes, etc?

Yes! Thank you! 🙏

**Comment by shcheklein** [comment]
@dreadatour can this be closed?

**Comment by dreadatour** [comment]
Yes, thank you 🙏
